### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hemanth** [hemanth/jsfeatures.in#1]
- [x] Create `es5` and `es7` data files.
- [x] Make `Feature` component to accept `spec` prop.
- [x] Favicon.
- [x] Footer.
- [x] Meta tags?
- [x] Auto sync `gh-pages`with `master`: `gulp`?
- [x] Display more info about all the features.
- [ ] Link to `mdn` and `specs` 
- [x] Autogen `sitemap`
- [x] HTTPS
- [x] Offline support with service workers.
- [x] Add to home screen.
- [ ] WPO: Loadtime, caching et.al
- [x] Better design

**Comment by hemanth** [comment]
//cc @shidhincr @gokulkrishh

**Comment by gokulkrishh** [comment]
<img width="705" alt="screen shot 2016-07-27 at 2 49 51 pm" src="https://cloud.githubusercontent.com/assets/2944237/17170439/aa1173f4-5409-11e6-9db0-5bbd951af49c.png">

**1. we can cache prism js & css and icon**

and total size is 

<img width="732" alt="screen shot 2016-07-27 at 2 53 30 pm" src="https://cloud.githubusercontent.com/assets/2944237/17170499/f1bc0a52-5409-11e6-892e-37334f8b1b08.png">

**Comment by hemanth** [comment]
Yeah, let us do that! 

Along with the lighthouse suggestions.
